### ISSUE TITLE
No longer works on cloud flare ?

### ISSUE THREAD

**Issue by gedw99** [iyouport-org/relaybaton#13]
I read that clodflare no longer allows both ESNI and SNI connections.

Can you let me know ?

I can build this into flutter and so build mobile and desktop apps using it.

**Comment by onoketa** [comment]
What Cloudflare does not allow is the inclusion of both SNI and ESNI extensions in Client Hello, whereas Relaybaton contains only ESNI extensions, which is allowed by Cloudflare.

**Comment by gedw99** [comment]
thank you for the explanation . make sense now.
